<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-0M17UIVA" failures="3" tests="6" name="Edso" time="0.109" errors="0" timestamp="2023-02-24T20:36:11 IST">
  <testcase classname="demo.reporting.ReportingExample" name="testCase1" time="0.025">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at demo.reporting.ReportingExample.testCase1(ReportingExample.java:10)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testCase1 -->
  <testcase classname="demo.reporting.ReportingExample" name="testCase2" time="0.001"/>
  <testcase classname="demo.reporting.ReportingExample" name="testCase3" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at demo.reporting.ReportingExample.testCase3(ReportingExample.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testCase3 -->
  <testcase classname="demo.reporting.ReportingExample" name="testCase4" time="0.0"/>
  <testcase classname="demo.reporting.ReportingExample" name="testCase5" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at demo.reporting.ReportingExample.testCase5(ReportingExample.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testCase5 -->
  <testcase classname="demo.reporting.ReportingExample" name="testCase6" time="0.001"/>
</testsuite> <!-- Edso -->
